# Generated by Django 3.1.3 on 2020-11-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_api', '0002_auto_20201118_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ansewruser',
            old_name='user_answer',
            new_name='text_answer',
        ),
        migrations.AddField(
            model_name='ansewruser',
            name='choice_answer',
            field=models.ManyToManyField(to='questionnaire_api.Answer'),
        ),
    ]
