# Generated by Django 3.1.3 on 2020-11-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_api', '0004_auto_20201115_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='date_stop',
            field=models.DateField(blank=True, null=True),
        ),
    ]
