# Generated by Django 3.1.3 on 2020-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_api', '0004_auto_20201118_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansewruser',
            name='choice_answer',
            field=models.ManyToManyField(blank=True, to='questionnaire_api.Answer'),
        ),
    ]
