# Generated by Django 3.1.3 on 2020-11-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_api', '0005_auto_20201118_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnsewrUser',
        ),
    ]
